Big move to auto* tools.
Let's rely on autotools from now on. A few bugs can still remain.

[kir@openvz.org: using .in files as source, various cleanups]

diff --git a/bin/vznetcfg.in b/bin/vznetcfg.in
--- a/bin/vznetcfg.in
+++ b/bin/vznetcfg.in
@@ -15,32 +15,44 @@
 #  along with this program; if not, write to the Free Software
 #  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 #
-#
-# This script removes routing for given VE.
-#
-# Parameters are passed in environment variables.
-# Required parameters:
-#   IP_ADDR       - IPs to delete, several addresses should be divided by space
-#   VEID          - VE id
-# Optional parameters:
-#   VE_STATE      - state of VE; could be one of:
-#                     starting | stopping | running | stopped
+VZNETCFG=@PKGCONFDIR@/vznet.conf
 
-. /usr/lib/vzctl/scripts/vps-functions
+[ -f ${VZNETCFG} ] && source ${VZNETCFG}
 
-vzcheckvar IP_ADDR VEID
+function usage()
+{
+	echo "vznetcfg init veth <dev>"
+}
 
-vzgetnetdev
+function init_veth()
+{
+	local dev=$1
 
-for IP in $IP_ADDR; do
-	vzdelrouting $IP
-	vzarp del $IP
-	# Update ip address information
-	if [ "${VE_STATE}" = "running" -a -f "${VE_STATE_DIR}/${VEID}" ]; then
-		cat ${VE_STATE_DIR}/${VEID} | tr ' ' '\n' | \
-		grep -w -v "${IP}" | tr '\n' ' ' > ${VE_STATE_DIR}/${VEID}
-	fi		
-done
+	/sbin/ifconfig ${dev} up
+}
+# Call the external script if defined
+if [ -n "${EXTERNAL_SCRIPT}" -a -x "${EXTERNAL_SCRIPT}" ]; then
+	export VEID
+	exec ${EXTERNAL_SCRIPT} $@
+fi
 
+if test $# -le 2; then
+    usage
+    exit 0
+fi
+
+CMD=$1
+case "${CMD}$2" in
+	initveth)
+		if test $# -ne 3; then
+			usage
+			exit 1
+		fi
+		init_veth $3
+		;;
+	*)
+		echo "invalid action"
+		exit 1
+		;;
+esac
 exit 0
-# end of script
diff --git a/etc/ifdown-venet.in b/etc/ifdown-venet.in
--- a/etc/ifdown-venet.in
+++ b/etc/ifdown-venet.in
@@ -15,44 +15,22 @@
 #  along with this program; if not, write to the Free Software
 #  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 #
-VZNETCFG=/etc/vz/vznet.conf
 
-[ -f ${VZNETCFG} ] && source ${VZNETCFG}
+test -f @PKGCONFDIR@/vz.conf || exit 1
+test -f @PKGLIBDIR@/scripts/vps-functions || exit 1
+test -f /etc/init.d/functions && . /etc/init.d/functions
 
-function usage()
-{
-	echo "vznetcfg init veth <dev>"
-}
-
-function init_veth()
-{
-	local dev=$1
-
-	/sbin/ifconfig ${dev} up
-}
-# Call the external script if defined
-if [ -n "${EXTERNAL_SCRIPT}" -a -x "${EXTERNAL_SCRIPT}" ]; then
-	export VEID
-	exec ${EXTERNAL_SCRIPT} $@
-fi
-
-if test $# -le 2; then
-    usage
-    exit 0
-fi
-
-CMD=$1
-case "${CMD}$2" in
-	initveth)
-		if test $# -ne 3; then
-			usage
-			exit 1
-		fi
-		init_veth $3
-		;;
-	*)
-		echo "invalid action"
+## SuSE distro
+if [ -f /etc/sysconfig/network/scripts/functions ]; then
+	vznet=$1
+else
+	CONFIG=${1}
+	if ! . "$CONFIG"; then
+		echo "can't source interface config $CONFIG" >&2
 		exit 1
-		;;
-esac
-exit 0
+	fi
+	vznet=$DEVICE
+fi
+
+echo "Shutting down interface $vznet: " 
+ip link set $vznet down
diff --git a/etc/ifup-venet.in b/etc/ifup-venet.in
--- a/etc/ifup-venet.in
+++ b/etc/ifup-venet.in
@@ -16,9 +16,13 @@
 #  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 #
 
-test -f /etc/vz/vz.conf || exit 1
-test -f /usr/lib/vzctl/scripts/vps-functions || exit 1
+VZCONF=@PKGCONFDIR@/vz.conf
+test -f ${VZCONF} || exit 1
+test -f @PKGLIBDIR@/scripts/vps-functions || exit 1
 test -f /etc/init.d/functions && . /etc/init.d/functions
+
+# configure VZNET
+modvenet="vznetdev vznet"
 
 ## SuSE distro
 if [ -f /etc/sysconfig/network/scripts/functions ]; then
@@ -31,6 +35,42 @@ else
 	fi
 	vznet=$DEVICE
 fi
+. @PKGLIBDIR@/scripts/vps-functions
+. ${VZCONF}
 
-echo "Shutting down interface $vznet: " 
-ip link set $vznet down
+veinfo="/proc/vz/veinfo"
+
+# configure interface
+
+for mod in ${modvenet}; do
+	modprobe ${mod} 2>/dev/null
+done
+
+if [ ! -r $veinfo ]; then
+	echo "can't find venet kernel module" >&2
+	exit 1
+fi
+
+ip link set $vznet up
+
+echo "Bringing up interface $vznet: " 
+ip addr add 0.0.0.0/0 dev $vznet
+
+echo "Configuring interface $vznet: " 
+sysctl -w net.ipv4.conf.$vznet.send_redirects=0
+
+if [ "${IPV6}" = "yes" ]; then
+	echo "Configuring ipv6 $vznet: "
+	# Fix me: ip addres should be generated
+	ip -6 addr add fe80::1/128 dev $vznet
+fi
+
+if [ -r $veinfo ]; then
+	vzgetnetdev
+
+	for veip in `awk '($1 > 0) { for(i=4;i<=NF;i++) { print $i; } }' < $veinfo`; do
+		vzarp add $veip
+		vzaddrouting $veip
+	done
+fi
+
