put_param3() can incorrectly set $name=( "" )

diff --git a/etc/dists/scripts/functions b/etc/dists/scripts/functions
--- a/etc/dists/scripts/functions
+++ b/etc/dists/scripts/functions
@@ -130,7 +130,11 @@ function put_param3() {
 		fi
 		mv -f ${file}.$$ ${file}
 	else
-		echo "$name=( \"$value\" )" >> $file || error "Can't change file $file" $VZ_FS_NO_DISK_SPACE
+		if [ -z "${value}" ]; then
+			echo "$name=( )" >> $file || error "Can't change file $file" $VZ_FS_NO_DISK_SPACE
+		else
+			echo "$name=( \"$value\" )" >> $file || error "Can't change file $file" $VZ_FS_NO_DISK_SPACE
+		fi
 	fi
 }
 
