Use /proc/vz/vestat for running VE listing Various vzctl scripts use /proc/vz/veinfo as an indicator of OpenVZ running on HN. But this file appears only after venet module is loaded. This module easily can not be loaded, but OpenVZ works. /proc/vz/vestat is much better indicator. This patch produces considered replacement.

diff --git a/etc/ifup-venet b/etc/ifup-venet
--- a/etc/ifup-venet
+++ b/etc/ifup-venet
@@ -45,6 +45,12 @@ veinfo="/proc/vz/veinfo"
 for mod in ${modvenet}; do
 	modprobe ${mod} 2>/dev/null
 done
+
+if [ ! -r $veinfo ]; then
+	echo "can't find venet kernel module" >&2
+	exit 1
+fi
+
 ip link set $vznet up
 
 echo "Bringing up interface $vznet: " 
